import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navgation from "../components/navigation";
import Footer from "../components/footer";
import Layout from "../components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
